export const SelectionState = {
    NOT_IN_PROGRESS: "NOT_IN_PROGRESS",
    IS_CHOOSING_THE_MODE: "IS_CHOOSING_THE_MODE",
    NEW_POINT: "NEW_POINT",
    EXISTING_POINT: "EXISTING_POINT",
    MUNICIPALITY: "MUNICIPALITY",
    NEW_AREA: "NEW_AREA",
    CONFIRM_AREA: "CONFIRM_AREA",
    EXISTING_AREA: "EXISTING_AREA",
  };